version: "3.3"

volumes:
  db:

services:
  ui:
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/db/db.sqlite"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 3000:3000
    volumes:
      - db:/db
      - .:/app
    restart: unless-stopped
